(in-package :hvac)



;;; MATERIALS

(defclass material ()
  ((molw :accessor molw :initarg :molw)))

(defclass solid (material)
  ())

(defclass fluid (material)
  ())

(defclass liquid (fluid)
  ())

(defclass gas (fluid)
  ())



;;; All materials

(defgeneric rho (material &key tem p)
  (:documentation "Density [kg/m3]"))

(defgeneric cp (material &key tem p)
  (:documentation "Specific heat capacity [J/kg.K]"))

(defgeneric thcon (material &key tem p)
  (:documentation "Thermal Conductivity [W/m.K]"))

(defgeneric thdiff (material &key tem p)
  (:documentation "Thermal diffusivity"))



;;; Fluids

(defgeneric vis (fluid &key tem p)
  (:documentation "Viscosity [Pa.s]"))

(defgeneric kvis (fluid &key tem p)
  (:documentation "Kinematic viscosity [m2/s]"))

(defgeneric pr (fluid &key tem p)
  (:documentation "Prandtl number [--]"))

(defmethod pr ((fluid fluid) &key tem p)
  (/ (kvis fluid tem p)
     (thdiff fluid tem p)))



;;; Gases

(defgeneric r-gas (gas)
  (:documentation "Gas constant [J/kg.K]"))

(defmethod r-gas ((gas gas))
  (/ +universal-r-gas+ (molw gas)))



;;; AIR

(defparameter *air* (make-instance 'gas
                                   :molw 29e-3
                                   :density #'(lambda (tem p)
                                                (/ (* p (mw *air*))
                                                   (* +rgas+ tem)))
                                   :conductivity #2a((-183 0.0083)
                                                     (-173 0.0092)
                                                     (-163 0.0102)
                                                     (-153 0.0111)
                                                     (-143 0.0120)
                                                     (-140 0.0123)
                                                     (-133 0.0129)
                                                     (-123 0.0138)
                                                     (-113 0.0146)
                                                     (-93  0.0164)
                                                     (-73  0.0181)
                                                     (-53  0.0198)
                                                     (-33  0.0215)
                                                     (-13  0.0231)
                                                     (7    0.0246)
                                                     (27   0.0261)
                                                     (47   0.0276)
                                                     (67   0.0290)
                                                     (87   0.0304)
                                                     (107  0.0317)
                                                     (127  0.0331)
                                                     (147  0.0344)
                                                     (167  0.0357)
                                                     (187  0.0370)
                                                     (207  0.0383)
                                                     (227  0.0395)
                                                     (327  0.0456)
                                                     (377  0.0497)
                                                     (427  0.0524)
                                                     (477  0.0549)
                                                     (1000 0.0549))

                                   :viscosity #2a((-183   0.00635)
                                                  (-173   0.00706)
                                                  (-163   0.00775)
                                                  (-153   0.00843)
                                                  (-143   0.00909)
                                                  (-140   0.00929)
                                                  (-133   0.00974)
                                                  (-123   0.01038)
                                                  (-113   0.0110)
                                                  (-93    0.0122)
                                                  (-73    0.0134)
                                                  (-53    0.0145)
                                                  (-33    0.0155)
                                                  (-13    0.0166)
                                                  (7      0.0176)
                                                  (27     0.0185)
                                                  (47     0.0195)
                                                  (67     0.0204)
                                                  (87     0.0213)
                                                  (107    0.0221)
                                                  (127    0.0229)
                                                  (147    0.0238)
                                                  (167    0.0245)
                                                  (187    0.0253)
                                                  (207    0.0261)
                                                  (227    0.0268)
                                                  (327    0.0303)
                                                  (377    0.03225)
                                                  (427    0.03388)
                                                  (477    0.03546)
                                                  (1000   0.03546))))

(defmethod rho ((mat air) &key tem p)
  (declare (ignore mat tem p))
  1.18)

(defun array-interpolate (matrix x)
  (let ((pos (position )))))

(defparameter *air-viscosity* #2a((-183   0.00635)
                                  (-173   0.00706)
                                  (-163   0.00775)
                                  (-153   0.00843)
                                  (-143   0.00909)
                                  (-140   0.00929)
                                  (-133   0.00974)
                                  (-123   0.01038)
                                  (-113   0.0110)
                                  (-93    0.0122)
                                  (-73    0.0134)
                                  (-53    0.0145)
                                  (-33    0.0155)
                                  (-13    0.0166)
                                  (7      0.0176)
                                  (27     0.0185)
                                  (47     0.0195)
                                  (67     0.0204)
                                  (87     0.0213)
                                  (107    0.0221)
                                  (127    0.0229)
                                  (147    0.0238)
                                  (167    0.0245)
                                  (187    0.0253)
                                  (207    0.0261)
                                  (227    0.0268)
                                  (327    0.0303)
                                  (377    0.03225)
                                  (427    0.03388)
                                  (477    0.03546)
                                  (487    0.03546)
                                  (1000   0.03546)))

(defparameter *isobaric-water-properties*
  )
;; ;;; ------------------------------------------------------------
;; ;;; MATTER
;; ;;; ------------------------------------------------------------
;; (defclass matter ()
;;   ((molecular-weight :initarg :molecular-weight :reader molecular-weight)
;;    (density          :initarg :density          :reader density)
;;    (conductivity     :initarg :conductivity     :reader conductivity)
;;    (specific-heat    :initarg :specific-heat    :reader specific-heat)))

;; (defclass solid (matter)
;;   ())

;; (defclass fluid (matter)
;;   ((viscosity :initarg :viscosity :reader viscosity)))

;; (defclass gas (fluid)
;;   ())

;; (defclass liquid (fluid)
;;   ())


;; ;;; --- Functions for properties of matter ---

;; (defgeneric rho (matter tem &optional pres)
;;   (:documentation "Density"))

;; (defmethod rho ((mat matter) tem &optional pres)
;;   (declare (ignore pres))
;;   (funcall (density mat) tem))

;; (defmethod rho ((mat gas) tem &optional (pres +patm+))
;;   (funcall (density mat) tem pres))

;; (defun mw (matter)
;;   "Molecular weight"
;;   (molecular-weight matter))

;; (defun con (matter tem)
;;   "Conductivity"
;;   (funcall (conductivity matter) tem))

;; (defun cp (matter tem)
;;   "Heat capacity at constant pressure"
;;   (funcall (specific-heat matter) tem))

;; (defun thdiff (matter tem &optional (pres +patm+))
;;   "Thermal diffusivity"
;;   (/ (con matter tem)
;;      (* (rho matter tem pres)
;;      (cp matter tem))))

;; (defun vis (fluid tem)
;;   "Viscosity"
;;   (funcall (viscosity fluid) tem))

;; (defun kvis (fluid tem &optional (pres +patm+))
;;   "Kinematic viscosity"
;;   (/ (vis fluid tem) (rho fluid tem pres)))

;; (defun pr (fluid tem &optional (pres +patm+))
;;   "Prandtl number"
;;   (/ (kvis fluid tem pres)
;;      (thdiff fluid tem pres)))


;; ;;; ------------------------------------------------------------
;; ;;; SOLID DEFINITIONS
;; ;;; ------------------------------------------------------------
;; (defparameter *aluminum*
;;   (make-instance 'solid
;;               :conductivity (constantly 237)))

;;; ------------------------------------------------------------
;;; FLUID DEFINITIONS
;;; ------------------------------------------------------------
;; (defparameter *air*
;;   (make-instance 'gas
;;               :molecular-weight 29d-3
;;               :density #'(lambda (tem p)
;;                            (/ (* p (mw *air*))
;;                               (* +rgas+ tem)))
;;               :conductivity (lambda-table #2a((-183 0.0083)
;;                                               (-173 0.0092)
;;                                               (-163 0.0102)
;;                                               (-153 0.0111)
;;                                               (-143 0.0120)
;;                                               (-140 0.0123)
;;                                               (-133 0.0129)
;;                                               (-123 0.0138)
;;                                               (-113 0.0146)
;;                                               (-93  0.0164)
;;                                               (-73  0.0181)
;;                                               (-53  0.0198)
;;                                               (-33  0.0215)
;;                                               (-13  0.0231)
;;                                               (7    0.0246)
;;                                               (27   0.0261)
;;                                               (47   0.0276)
;;                                               (67   0.0290)
;;                                               (87   0.0304)
;;                                               (107  0.0317)
;;                                               (127  0.0331)
;;                                               (147  0.0344)
;;                                               (167  0.0357)
;;                                               (187  0.0370)
;;                                               (207  0.0383)
;;                                               (227  0.0395)
;;                                               (327  0.0456)
;;                                               (377  0.0497)
;;                                               (427  0.0524)
;;                                               (477  0.0549)
;;                                               (1000 0.0549))
;;                                           :arg-fn #'(lambda (x) (to-unit x "K" "C")))
;;               :viscosity (lambda-table #2a((-183   0.00635)
;;                                            (-173   0.00706)
;;                                            (-163   0.00775)
;;                                            (-153   0.00843)
;;                                            (-143   0.00909)
;;                                            (-140   0.00929)
;;                                            (-133   0.00974)
;;                                            (-123   0.01038)
;;                                            (-113   0.0110)
;;                                            (-93    0.0122)
;;                                            (-73    0.0134)
;;                                            (-53    0.0145)
;;                                            (-33    0.0155)
;;                                            (-13    0.0166)
;;                                            (7      0.0176)
;;                                            (27     0.0185)
;;                                            (47     0.0195)
;;                                            (67     0.0204)
;;                                            (87     0.0213)
;;                                            (107    0.0221)
;;                                            (127    0.0229)
;;                                            (147    0.0238)
;;                                            (167    0.0245)
;;                                            (187    0.0253)
;;                                            (207    0.0261)
;;                                            (227    0.0268)
;;                                            (327    0.0303)
;;                                            (377    0.03225)
;;                                            (427    0.03388)
;;                                            (477    0.03546)
;;                                            (1000   0.03546))
;;                                        :arg-fn #'(lambda (x) (to-unit x "K" "C"))
;;                                        :val-fn #'(lambda (y) (* y 1e-3)))
;;               :specific-heat (lambda-table #2a((-173 1.028)
;;                                                (-163 1.022)
;;                                                (-153 1.017)
;;                                                (-143 1.014)
;;                                                (-140 1.013)
;;                                                (-133 1.012)
;;                                                (-123 1.011)
;;                                                (-113 1.009)
;;                                                (-93  1.007)
;;                                                (-73  1.006)
;;                                                (-53  1.006)
;;                                                (-33  1.005)
;;                                                (-13  1.005)
;;                                                (7    1.006)
;;                                                (27   1.006)
;;                                                (47   1.007)
;;                                                (67   1.008)
;;                                                (87   1.010)
;;                                                (107  1.012)
;;                                                (127  1.014)
;;                                                (147  1.017)
;;                                                (167  1.020)
;;                                                (187  1.023)
;;                                                (207  1.026)
;;                                                (227  1.030)
;;                                                (327  1.052)
;;                                                (377  1.063)
;;                                                (427  1.075)
;;                                                (477  1.087)
;;                                                (1000  1.087))
;;                                            :arg-fn #'(lambda (x) (to-unit x "K" "C"))
;;                                            :val-fn #'(lambda (y) (* y 1e+3)))))


;; (defparameter *water*
;;   (make-instance 'liquid
;;               :molecular-weight 18d-3
;;               :density (lambda-table #2a((0.01 1.0002)
;;                                          (2    1.0001)
;;                                          (4    1.0001)
;;                                          (6    1.0001)
;;                                          (8    1.0002)
;;                                          (10   1.0004)
;;                                          (12   1.0005)
;;                                          (14   1.0008)
;;                                          (16   1.0011)
;;                                          (18   1.0014)
;;                                          (20   1.0018)
;;                                          (22   1.0022)
;;                                          (24   1.0027)
;;                                          (26   1.0032)
;;                                          (28   1.0037)
;;                                          (30   1.0043)
;;                                          (32   1.0050)
;;                                          (34   1.0056)
;;                                          (36   1.0063)
;;                                          (38   1.0071)
;;                                          (40   1.0078)
;;                                          (42   1.0056)
;;                                          (44   1.0095)
;;                                          (46   1.0103)
;;                                          (48   1.0112)
;;                                          (50   1.0121)
;;                                          (52   1.0131)
;;                                          (54   1.0141)
;;                                          (56   1.0151)
;;                                          (58   1.0161)
;;                                          (60   1.0172)
;;                                          (62   1.0182)
;;                                          (64   1.0194)
;;                                          (66   1.0205)
;;                                          (68   1.0217)
;;                                          (70   1.0228)
;;                                          (72   1.0240)
;;                                          (74   1.0253)
;;                                          (76   1.0265)
;;                                          (78   1.0278)
;;                                          (80   1.0291)
;;                                          (82   1.0308)
;;                                          (84   1.0318)
;;                                          (86   1.0332)
;;                                          (88   1.0346)
;;                                          (90   1.0360)
;;                                          (92   1.0375)
;;                                          (94   1.0389)
;;                                          (96   1.0404)
;;                                          (89   1.0420)
;;                                          (100  1.0435)
;;                                          (102  1.0451)
;;                                          (104  1.0467)
;;                                          (106  1.0483)
;;                                          (108  1.0499)
;;                                          (110  1.0516)
;;                                          (112  1.0533)
;;                                          (114  1.0550)
;;                                          (116  1.0568)
;;                                          (118  1.0585)
;;                                          (120  1.0603)
;;                                          (122  1.0622))
;;                                      :arg-fn #'(lambda (x) (to-unit x "K" "C"))
;;                                      :val-fn #'(lambda (y) (/ 1 (* y 1e-3))))
;;               :conductivity (lambda-table #2a((0    0.569)
;;                                               (4    0.578)
;;                                               (10   0.587)
;;                                               (16   0.597)
;;                                               (21   0.606)
;;                                               (27   0.613)
;;                                               (32   0.621)
;;                                               (38   0.628)
;;                                               (19   0.642)
;;                                               (60   0.654)
;;                                               (71   0.663)
;;                                               (82   0.672)
;;                                               (93   0.678)
;;                                               (100  0.682)
;;                                               (104  0.684)
;;                                               (116  0.687)
;;                                               (127  0.689)
;;                                               (138  0.689)
;;                                               (149  0.687)
;;                                               (160  0.685)
;;                                               (171  0.682)
;;                                               (183  0.677)
;;                                               (205  0.663)
;;                                               (260  0.604)
;;                                               (316  0.512))
;;                                           :arg-fn #'(lambda (x) (to-unit x "K" "C")))
;;               :viscosity (lambda-table #2a((0    1.75)
;;                                            (4    1.51)
;;                                            (10   1.28)
;;                                            (16   1.09)
;;                                            (21   0.947)
;;                                            (27   0.831)
;;                                            (32   0.732)
;;                                            (38   0.653)
;;                                            (19   0.533)
;;                                            (60   0.446)
;;                                            (71   0.383)
;;                                            (82   0.332)
;;                                            (93   0.293)
;;                                            (100  0.273)
;;                                            (104  0.261)
;;                                            (116  0.234)
;;                                            (127  0.213)
;;                                            (138  0.195)
;;                                            (149  0.179)
;;                                            (160  0.166)
;;                                            (171  0.155)
;;                                            (183  0.145)
;;                                            (205  0.129)
;;                                            (260  0.103)
;;                                            (316  0.0814))
;;                                        :arg-fn #'(lambda (x) (to-unit x "K" "C"))
;;                                        :val-fn #'(lambda (y) (* y 1e-3)))
;;               :specific-heat (lambda-table #2a((0    4216)
;;                                                (4    4208)
;;                                                (10   4199)
;;                                                (16   4191)
;;                                                (21   4187)
;;                                                (27   4183)
;;                                                (32   4178)
;;                                                (38   4178)
;;                                                (19   4178)
;;                                                (60   4187)
;;                                                (71   4191)
;;                                                (82   4199)
;;                                                (93   4212)
;;                                                (100  4220)
;;                                                (104  4224)
;;                                                (116  4241)
;;                                                (127  4258)
;;                                                (138  4280)
;;                                                (149  4308)
;;                                                (160  4354)
;;                                                (171  4409)
;;                                                (183  4463)
;;                                                (205  4543)
;;                                                (260  4940)
;;                                                (316  6397))
;;                                            :arg-fn (lambda (x) (to-unit x "K" "C")))))
